### PR TITLE
Python3.8 multiprocessing support

### PR DESCRIPTION
**Pull request by janjaapdriessen**
On python3.8 I get the error:

```
...
AttributeError: Can't pickle local object 'code_analysis.<locals>.taskrunner'
```

Moving `def taskrunner` to the module level fixes this issue. I don't see a test case for multiprocessing, and the version pins in buildout.cfg are a bit outdated. Let's see whether the tests pass on travis on python3.8.

### CODE REVIEW

**Comment by janjaapdriessen** [comment]
I did the contributor agreement dance, waiting for approval.

**Comment by tisto** [comment]
@janjaapdriessen can you provide steps to reproduce? We are running stuff on 3.8 and I never saw the error above.

**Comment by janjaapdriessen** [comment]
I added the `multiprocessing` setting to this repo's own [buildout config](27795864157a32e0fd24a8aed8877b3f7652151a) and ran buildout with python3.8.5 (I had to remove the version pins for zope.i18nmessageid and zope.security in order to install all dependencies). Running `bin/code-analysis` gives the pickle attribute error only when I move the `taskrunner` back inside the `code_analysis` function.

**Comment by janjaapdriessen** [comment]
@tisto could you have a look at this PR again please? You might have missed my last comment, I didn't mention you.

**Comment by tisto** [comment]
@janjaapdriessen the problem is that Travis is red (most likely unrelated to your PR) which makes it impossible to merge and release this PR right now. Unfortunately, I do not have the time to look into it. I am happy to merge PRs and do a release but I can not work on fixing things these days...

**Comment by janjaapdriessen** [comment]
@tisto I asked @sirex to revive rubygemsrecipe from bitbucket, there is a [0.3.0 release](https://lab.nexedi.com/nexedi/rubygemsrecipe/) that makes the buildout work again, we no longer need to run buildout twice, which is nice. 
However, I can not get the travis builds to work on python2.7, because of [an issue](https://github.com/jaraco/zipp/issues/50) with newer versions of `zipp`, zipp < 2 only installs with  older versions of pip/setuptools. Would you be okay with removing 2.7 support?

**Comment by tisto** [comment]
@janjaapdriessen I'd prefer to keep the Python 2 compatibility for a while. At least as long as Plone 5.2 is the main Plone release and still supports Python 2. We will break tons of existing buildouts when we drop Python2 support. The zipp issue should be fixable.

**Comment by janjaapdriessen** [comment]
Continuing in [another PR](https://github.com/plone/plone.recipe.codeanalysis/pull/230) because I opened this PR before signing the contributors agreement.

**Pull request closed without merging**
