### PR TITLE
Add flake8-isort.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
@gforcada code-analysis fails after adding flake8-isort on my machine:

```
ImportError: 'module' object has no attribute 'Flake8IsortChecker'
```

**Comment by tisto** [comment]
https://travis-ci.org/plone/plone.recipe.codeanalysis/jobs/80188030

**Comment by gforcada** [comment]
@tisto will look at it at night, probably some copy & paste error (I basically copy&pasted flake8-plone-api code into this one, so some leftovers are around probably)

**Comment by gforcada** [comment]
I had to remove all caches to make travis run, that's weird...

Anyway is still failing because the default sorting on isort is the sections and not alphabetically, we need to add an ``.isort.cfg`` file.

**Comment by gforcada** [comment]
Unfortunately we are hitting https://github.com/timothycrosley/isort/pull/327

So we can either not enable it for p.r.codeanalysis and just document it (like the other flake8 plugins) or first fix the upstream problem.

I will try to work on the upstream problem on the weekend.

**Comment by gforcada** [comment]
Seems the issue is already fixed, we are missing a new release with it :-) I already asked it.

**Comment by gforcada** [comment]
We got a new release! Let's see what travis says :-)

**Comment by gforcada** [comment]
Tests pass, so given that #160 is already merged, we could make a new release with this, what do you think?

**Comment by tisto** [comment]
@gforcada will make a release later today...

**Pull request merged**
