### PR TITLE
Full python3 support

### PR DESCRIPTION
**Pull request by gyst**
- This revives #161 to add SCSSLint, XMLLint, ChameleonLint support.
- Pull in a python3 update of ``i18ndude``, from source for now
- Also pull in a noncritical ``zc.buildout`` update to suppress some ``ResourceWarning``
- Add a linter based on ``z3c.dependencychecker``.

Also: Work around pip namespacing issue breaking Travis. The pip namespacing bug is biting hard. I've fixed Travis bootstrapping but had to remove coverage since this is broken, as is a Tox build which I did not add. 

This now has all tests green on all builds. I've tightened the Travis compatibility matrix by making all tests critical. There's a bit of a kludge involved in running buildout twice to get the ``scss-lint`` gem properly installed.

TODO:
- replace source checkout of ``i18ndude`` with a proper release (critical, awaiting release pending merge of https://github.com/collective/i18ndude/pull/48)
- replace source checkout of ``zc.buildout`` with a pin (noncritical)

### CODE REVIEW

**Comment by gyst** [comment]
Aw I now see there's also a new `ChameleonLint` included. Will add tests for that.

**Comment by gyst** [comment]
I'm about done with this and would appreciate review comments so I can finish this up. @tisto @gforcada ?

**Comment by gforcada** [comment]
@gyst first of all... hats off! :clap: thanks for this tremendous effort!

My laptop broke last week, I could do a last minute backup so not big losses, mostly my ability to contribute these days, so unfortunately I will have to delay my review a few days/weeks if that's not so much of a problem for you. TIA!

**Comment by jensens** [comment]
What's the state here? I would like to see it merged!

**Comment by gyst** [comment]
This is green. We've been using it "in production" (obviously just within our development/commit workflow) without a hitch.

I do have a plan to add some extra features, specifically an option to choose a `pre-push` hook instead of a `pre-commit` hook. But that's no reason to hold this PR.

**Comment by jensens** [comment]
Thanks @gyst 
It's a good bunch of changes and I am not able to review them all.
I would go for a merge and going an agile path of fixing in case something breaks.
If there are any problems occurring after merge, are you able (time-wise) to help fixing them?

**Comment by gyst** [comment]
Sure I'm happy to fix forward. I do need a reproduction though if somebody has breakage, i.e. a package with a buildout that enables me to reproduce a reported error. Note that while all the tests pass on py2 I'm using this myself on py3, so py2 is a bit less heavily stress tested. But again, I'll fix.

**Pull request merged**
