### PR TITLE
WIP install isort script

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by hvelarde** [comment]
+1

**Comment by gforcada** [comment]
@jensens I also like to close pull requests (better if they can be merged) but if they are labeled WIP, please **DON'T**. I was exploring some other approaches as to not have to install it this way as isort already installs a script by itself if installed by pip.

**Comment by jensens** [comment]
OPS, mea culpa, may I need more coffee. I'll revert ok?

**Comment by gforcada** [comment]
@jensens no worries, I don't think it needs to be reverted, but I wanted to polish a bit more before merging it, it can be done as a second pull request :-)

**Pull request merged**
