### PR TITLE
Overrides and push hook

### PR DESCRIPTION
**Pull request by gyst**
This introduces pre-push hooks, and a developer-local configuration override option so individual developers can choose locally whether they want to run pre-commit checks, pre-push checks, or both.

Additionally this contains some syntax cleanups to stop the Plone Jenkins linter complaining :-).

### CODE REVIEW

**Comment by gyst** [comment]
Beats me why the buildout self-tests within the test suite break, only on py27, only on Travis. Cannot reproduce locally

More info see debug job to inspect this at https://travis-ci.org/plone/plone.recipe.codeanalysis/jobs/384016060

**Comment by gyst** [comment]
This is now ready for merge.

**Comment by gyst** [comment]
@jensens Thanks for merging. Can we please get a 2.4.0 release on pypi? I don't want to maintain internal egg releases for all my projects.

**Comment by tisto** [comment]
@gyst no breaking changes or changes of the recipe params in the recent merges? /me is wondering if that should be a 3.0.0 release.

**Comment by gyst** [comment]
I think this warrants a 3.0.0 release, yes. Though it only breaks backward compatibility for python2.6, support for which is dropped. On all other counts this should be a drop-in upgrade, but it pulls in a chunk of `i18ndude` work I did which was a major version bump over there, and there may be other version pin changes that this is tested with which can obscure problems with older versions of those dependencies - the Travis 2.7 problems are an indicator.

**Pull request merged**
