### PR TITLE
New extra: plone

### PR DESCRIPTION
**Pull request by gforcada**
p.r.codeanalysis is meant to be general purpose tool rather than a plone-only tool.

Thus it does not make sense to add on the recommended list of flake8 plugins the ones that are plone specific.

To that extend a new extra is born: ``plone``.

### CODE REVIEW

**Comment by tisto** [comment]
@gforcada p.r.codeanalysis was meant to be to be useful for any buildout-based project. Though, 99% of the users are most likely plone users. Therefore I'm not sure if it make much sense to make it more complex for the 99% just to serve the 1% (and they don't even have any real disadvantage).

**Comment by jensens** [comment]
So whats the state here? I agree we should primary support Plone. So there is currently no way to install without Plone specific addons.

But do the installed Plone addons pull in some nasty dependency? Or is it just dead code?

In latter case I would not mind at all, since the plugins can be configured individually.

**Comment by iham** [comment]
as it is a **plone**-recipe i thought it is already a plone-related package...

**Comment by adamcheasley** [comment]
I have never seen buildout used outside the plone community. If this is a tool which requires buildout, then I don't see it being used much outside the plone community anyway.

**Comment by icemac** [comment]
@adamcheasley There are actually people using zc.buildout outside plone: We use it for union.cms a CMS based on Zope 2 but not on Plone. There are even [buildout recipes for Django](https://pypi.python.org/pypi?:action=browse&c=512&c=523) although I do not know whether they are still used widely.
I'd personally like to use plone.recipe.codeanalysis outside Plone.

**Comment by adamcheasley** [comment]
@icemac I've seen the buildout recipes for django. I've never seen them used. No idea why anyone would want to either. I'm sure buildout is used outside of zope and plone, but I would imagine the percentage is tiny. As @tisto says, this would be a lot of work for that tiny percentage.

**Comment by tisto** [comment]
Just to be clear. This discussion is not about if p.r.codeanalysis can be used by other buildout-based projects (this is the case and will remain). This is just about the question if we make "plone" just one of the use-cases or if it still remains the main use case. We could also discuss to rename "recommended" to "plone". Though, I don't think this is worth the effort to be honest.

**Comment by jensens** [comment]
After all it seems this change was overall not accepted? I close this one (but do not delete the branch for now). If you think this was wrong please reopen and go on.

**Pull request closed without merging**
